export const office = {
  city: 'Indore, Madhya Pradesh',
  address: '201, Sapphire Plaza, Vijay Nagar, Indore, Madhya Pradesh 452010',
  phones: ['+91 98765 43210', '+91 98111 22004'],
  emails: ['info@ss-technologies.com', 'sales@ss-technologies.com', 'hr@ss-technologies.com'],
  whatsapp: '919876543210',
}

export const serviceList = [
  {
    slug: 'ai-development',
    title: 'AI Development',
    blurb: 'Custom AI products for Indian businesses — automation, chatbots, and data-driven apps that improve operations.',
    details: 'We design and ship AI that fits real Indian workflows: Hindi + English support, IST delivery, and models that run cost-effectively. From internal copilots to customer-facing assistants, the goal is fewer manual hours and clearer decisions.',
    image: '/assets/ai.jpg',
    points: ['Chatbots and internal copilots', 'Document and KYC intelligence', 'Automation for ops and support', 'Secure cloud deployment in India regions'],
  },
  {
    slug: 'machine-learning',
    title: 'Machine Learning',
    blurb: 'Predictive models and data pipelines that help Indian teams make faster, better decisions.',
    details: 'We build ML systems around the data you already have — sales, sensors, support tickets, or transactions. Models are trained, evaluated and monitored so they stay useful after launch, not just in a demo.',
    image: '/assets/ml.jpg',
    points: ['Forecasting and scoring models', 'Data pipelines and feature stores', 'Model monitoring and retraining', 'Dashboards your team can actually use'],
  },
  {
    slug: 'iot-solutions',
    title: 'IoT Solutions',
    blurb: 'Connected devices and live dashboards for factories, logistics and field operations across India.',
    details: 'From shop-floor sensors in Pithampur to fleet trackers on Indian highways, we connect hardware to cloud dashboards with alerts, role-based access and offline-tolerant sync.',
    image: '/assets/iot.jpg',
    points: ['Device onboarding and telemetry', 'Live maps and plant dashboards', 'Alerts on WhatsApp, SMS and email', 'Works with patchy 4G / plant Wi-Fi'],
  },
  {
    slug: 'hardware-integration',
    title: 'Hardware Integration',
    blurb: 'Reliable software-to-hardware connections for manufacturing, retail POS and smart devices.',
    details: 'Printers, scanners, weighbridges, biometric devices and industrial controllers rarely speak the same language. We write the glue so your software talks to the floor without daily firefighting.',
    image: '/assets/hardware.jpg',
    points: ['POS, printers and scanners', 'Biometric and attendance devices', 'PLC / industrial protocol bridges', 'On-site commissioning in India'],
  },
  {
    slug: 'mobile-app-development',
    title: 'Mobile App Development',
    blurb: 'High-quality Android, iOS and Flutter apps built for Indian users, UPI, GST and regional languages.',
    details: 'We ship apps people actually open: fast on mid-range Androids, UPI-ready payments, OTP login, and copy that works in Hindi and English. Play Store and App Store release support included.',
    image: '/assets/mobile.jpg',
    points: ['Android, iOS and Flutter', 'UPI, wallets and GST-ready flows', 'Hindi + English UX', 'Store listing and release support'],
  },
  {
    slug: 'web-design-development',
    title: 'Web Designing and Development',
    blurb: 'Modern websites, portals and web apps that look sharp and perform on Indian networks.',
    details: 'Marketing sites, customer portals and internal tools — designed to load quickly on 4G, stay accessible, and give your team a CMS or admin they can run without calling us every week.',
    image: '/assets/web.jpg',
    points: ['Brand sites and landing pages', 'Portals and web apps', 'SEO-ready structure', 'Admin panels for your team'],
  },
  {
    slug: 'ecommerce-development',
    title: 'Ecommerce Development',
    blurb: 'Secure stores with Razorpay/Paytm, GST invoices, and operations built for Indian commerce.',
    details: 'Catalogues, carts, offers, GST invoices and shipping partners — built for Indian buyers and operators. We connect Razorpay or Paytm, handle COD where needed, and keep the backend simple for warehouse staff.',
    image: '/assets/ecommerce.jpg',
    points: ['Razorpay / Paytm / UPI', 'GST invoices and inventory', 'Shipping and COD flows', 'Admin for orders and offers'],
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    blurb: 'SEO, social, content and paid campaigns that reach customers in metros and Tier-2 cities.',
    details: 'Creative and performance together: landing pages, SEO, Meta and Google ads, and content that speaks to Indian audiences — not generic global copy pasted into a deck.',
    image: '/assets/marketing.jpg',
    points: ['SEO and content systems', 'Meta and Google campaigns', 'Creative for India markets', 'Clear monthly reporting'],
  },
  {
    slug: 'optimization-management',
    title: 'Optimization Management',
    blurb: 'Performance, SEO and reliability programs that keep products fast on 4G and BharatNet.',
    details: 'After launch, products slow down. We audit Core Web Vitals, API latency, crash rates and SEO, then run a monthly program so the product stays fast and findable.',
    image: '/assets/office.jpg',
    points: ['Speed and Core Web Vitals', 'Uptime and error budgets', 'SEO health checks', 'Monthly improvement sprints'],
  },
  {
    slug: 'staff-augmentation',
    title: 'Staff Augmentation',
    blurb: 'Senior Indian designers and engineers who plug into your team in IST hours.',
    details: 'Need a React lead, a Flutter pair, or a designer who already understands Indian product constraints? We embed people into your Slack, Jira and standups — IST overlap, no timezone drama.',
    image: '/assets/staff.jpg',
    points: ['Designers, engineers, QA, PMs', 'Monthly or project engagements', 'IST hours and English/Hindi', 'Transparent weekly tracking'],
  },
]

export const projects = [
  {
    slug: 'loanmitra',
    category: 'FinTech · India',
    title: 'LoanMitra Lending App',
    desc: 'Faster KYC, eNACH and credit decisions for a Mumbai NBFC.',
    details: 'LoanMitra replaced a paper-heavy lending desk with a mobile + admin stack: Aadhaar-assisted KYC, eNACH mandates, credit scoring and a maker-checker console. Agents in the field could start a file in minutes instead of a day.',
    image: '/assets/project-1.jpg',
    stack: ['React Native', 'Node.js', 'AWS Mumbai', 'eNACH'],
    results: ['KYC time cut from days to minutes', 'eNACH success rate improved', 'Admin audit trail for RBI-ready ops'],
  },
  {
    slug: 'kiranakart',
    category: 'Retail · Mobile',
    title: 'KiranaKart Commerce',
    desc: 'Kirana delivery app with UPI, inventory and route planning for Indore stores.',
    details: 'Built for neighbourhood kiranas, not warehouse-first quick commerce. Store staff update stock on a simple Android app; riders get clustered routes; customers pay with UPI. Inventory stays honest because it is tied to what is actually on the shelf.',
    image: '/assets/project-2.jpg',
    stack: ['Flutter', 'Firebase', 'UPI', 'Maps'],
    results: ['Same-day delivery for 40+ stores', 'UPI as default checkout', 'Rider app used daily in Indore'],
  },
  {
    slug: 'mediseva',
    category: 'Healthcare · SaaS',
    title: 'MediSeva Care Suite',
    desc: 'OPD booking, e-prescriptions and reports for clinics in Pune and Jaipur.',
    details: 'A clinic suite for OPD queues, digital prescriptions, lab report sharing and reminders. Designed for front-desk staff who are busy, not for a Silicon Valley demo. Works on a laptop and a front-desk Android phone.',
    image: '/assets/project-3.jpg',
    stack: ['React', 'Node.js', 'PostgreSQL', 'WhatsApp API'],
    results: ['OPD wait visibility for patients', 'e-prescriptions printed or shared', 'Clinic onboarding in days, not months'],
  },
  {
    slug: 'fleetbharat',
    category: 'Logistics · Platform',
    title: 'FleetBharat Tracking',
    desc: 'Real-time truck visibility for a Delhi–NCR logistics group.',
    details: 'GPS, trip sheets, fuel events and GST-ready invoices in one console. Dispatchers see trucks on a live map; drivers get a lightweight app that survives weak network; finance gets cleaner trip data.',
    image: '/assets/project-4.jpg',
    stack: ['React', 'Go', 'MQTT', 'Maps'],
    results: ['Live fleet on one map', 'Fewer missing trip sheets', 'GST-ready invoice export'],
  },
  {
    slug: 'padhaisathi',
    category: 'EdTech · Mobile',
    title: 'PadhaiSathi Learning',
    desc: 'Hindi + English learning app for students in Tier-2 cities.',
    details: 'Lessons, quizzes and teacher assignments in Hindi and English, with low-data video and offline packs. Built so a student on a ₹10k Android phone can actually finish a chapter.',
    image: '/assets/project-5.jpg',
    stack: ['Flutter', 'Node.js', 'HLS video', 'Offline cache'],
    results: ['Bilingual lessons by default', 'Offline chapter packs', 'Teachers assign work from a simple web console'],
  },
  {
    slug: 'karkhana-pulse',
    category: 'Manufacturing · IoT',
    title: 'Karkhana Pulse',
    desc: 'Machine monitoring for an auto-component plant in Pithampur, Indore.',
    details: 'Sensors on critical machines stream OEE, downtime reasons and alerts to a plant dashboard. Supervisors get WhatsApp pings when a line stops; management sees shift-wise output without walking the floor with a clipboard.',
    image: '/assets/project-6.jpg',
    stack: ['IoT gateways', 'Node.js', 'Grafana', 'WhatsApp'],
    results: ['Live OEE on the shop floor', 'Downtime reasons captured', 'Shift reports without manual Excel'],
  },
]

export const testimonials = [
  ['Arjun Kapoor', 'Product Head, FinTech · Mumbai', 'SS Mobile brought structure to a messy lending product. KYC, eNACH and the admin panel went live on time.'],
  ['Riya Mehta', 'COO, Retail Group · Ahmedabad', 'The team understood kirana operations, not just screens. Our delivery app is used daily by store staff.'],
  ['Vikram Shah', 'CTO, Healthcare · Pune', 'From UX to AWS deployment they worked like an extension of our internal team. Clinic onboarding became simple.'],
  ['Priya Nair', 'Founder, EdTech · Kochi', 'Clear communication, IST overlap, and a learning app our teachers actually enjoy using.'],
  ['Rahul Iyer', 'CEO, Logistics · Bengaluru', 'Fleet tracking, GST-ready invoices and a driver app — delivered without drama.'],
  ['Ananya Gupta', 'App Owner · Delhi NCR', 'Professional, fast and honest about scope. I would hire SS Mobile again for the next version.'],
]

export const clients = ['TATA', 'JIO', 'ZOMATO', 'PAYTM', 'PHONEPE', 'SWIGGY', 'FLIPKART', 'BYJU\'S']
